### ISSUE TITLE
Server Crashes On Loop Due To Ghast Fireball

### ISSUE THREAD

**Issue by Kuusotare** [leonardwohl/Good-Grief#1]
https://pastebin.com/7v23qVay

**Comment by leonardwohl** [comment]
Thanks for finding this! Fix will be up shortly :+1:

**Comment by leonardwohl** [comment]
@Kuusotare fix is available[ here on curseforge ](https://www.curseforge.com/minecraft/mc-mods/good-grief/files). Thanks again!
